import Link from "next/link"
import "../styles/global.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}) {
  const header = (
    <header className=" text-center bg-slate-800 p-8 my-6 rounded-md  " >
      <div>
        <Link href={"/"}> <h1 className="text-3xl font-bold  text-center text-white/90 ">Abdallah&apos;s Blog</h1> </Link>
        <nav>
        <Link href={"/create-post"} className=" text-white/40 ">Create Post </Link>
        {/* <span className=" text-white/40" >|</span> */}
        {/* <Link href={"/"} className=" text-white/40">All Posts</Link> */}
        </nav>
      </div>
    </header>
  )
  const footer = (
    <footer>
      <div className="border-t border-slate-500 mt-6 py-6 text-slate-400 text-center">
        <br/>
        <h3>Developed by Askar</h3>
      </div>
    </footer>
  )
  return (
    <html lang="en">
      <body>
        <div className="mx-auto max-w-2xl px-4">

        {header}
        {children}
        {footer}
        </div>
        </body>
    </html>
  )
}
